### ISSUE TITLE
Add end time?

### ISSUE THREAD

**Issue by ari-za** [wernerhp/ha_integration_load_shedding#2]
Hey man

Great work with the add on! 

Is it possible to add the end time of load shedding to the start time? 
Can call it "Next Schedule" instead of Next Start for example

e.g. Next Schedule: 8:00am - 10:30am

Or add another line to show the end time. I think it's useful to show the end time as well not just the start time, and I know it is returned in the same string from the Eskom API.

Also is it possible for you to format the time from the ISO format to a more normal format? Just going on the screenshots here, but glancing at the code looks like it might already be formatted?

Thanks!

**Comment by wernerhp** [comment]
If your area is supported, then the schedule data is available in the attributes as can be seen below.
![image](https://user-images.githubusercontent.com/2578772/168235381-0be471c0-4183-4df3-9c6c-8de4c335a7f5.png)
You can use this data to build your own sensors and panels in Home Assistant.
You can also change the formatting as you want it in Home Assistant.
The examples in the readme are just examples.  
I've tweaked my own panels a bit after using it for a while, so I'll update the examples which you can use as reference if you don't know how to do it.

**Comment by ari-za** [comment]
Awesome, thanks!

>
