### ISSUE TITLE
Update interval of integration

### ISSUE THREAD

**Issue by n00bster-za** [wernerhp/ha_integration_load_shedding#8]
thanks for the new code looks much better with new time formats. 

I have 1 last issue. Seems like I have to manually reload the integration before it will show values. Is this my HA instance that is not updating or is it the load shedding integration that needs to be change to update quicker? 

LS stared at 17h00 and after 20 min still did not see any info. Reload integration then values populate.

**Comment by wernerhp** [comment]
Yeah, I noticed it too. I think it's currently set to uodate every 30min. Also a problem because it runs every 30min from when you start HA. Will see jow it runs at every minute and post some updates when I get a chance

**Comment by wernerhp** [comment]
Updated the interval. Will be available in the next release
